using Microsoft.Maui.Controls;
using Microsoft.Maui.Controls.Shapes; // added for RoundRectangle
using Donezo.Services;
using Microsoft.Maui.Storage;
using Donezo.Pages.Components;
using System.Text.RegularExpressions;
using Microsoft.Maui.Layouts; // for AbsoluteLayoutFlags

namespace Donezo.Pages;

public class ManageAccountPage : ContentPage, IQueryAttributable
{
    private readonly INeonDbService _db; private DualHeaderView _dualHeader=null!; private int? _userId; private string _username=""; private Entry _usernameEntry=null!; private Entry _emailEntry=null!; private Entry _currentPasswordEntry=null!; private Entry _newPasswordEntry=null!; private Entry _confirmPasswordEntry=null!; private Button _saveProfileButton=null!; private Button _changePasswordButton=null!; private ActivityIndicator _loading=null!;
    // Separate message labels (replaces single _statusLabel)
    private Label _profileMessageLabel = null!; private Label _passwordMessageLabel = null!;
    // User menu overlay fields
    private Grid _pageRoot = null!; private AbsoluteLayout _pageOverlay = null!; private Grid _menuAlignGrid = null!; private Border _userMenuBorder = null!; private BoxView _menuScrim = null!; private bool _userMenuVisible;

    public ManageAccountPage():this(ServiceHelper.GetRequiredService<INeonDbService>()){}
    public ManageAccountPage(INeonDbService db){ _db=db; Title=""; Shell.SetNavBarIsVisible(this,false); BuildUi(); _=InitializeAsync(); }
    public void ApplyQueryAttributes(IDictionary<string, object> query){ if(query.TryGetValue("username",out var v) && v is string u && !string.IsNullOrWhiteSpace(u)){ _username=u; if(_dualHeader!=null) _dualHeader.Username=u; if(_userId==null) _=InitializeAsync(); } }
    private async Task InitializeAsync(){ try{ var stored= await SecureStorage.GetAsync("AUTH_USERNAME"); if(!string.IsNullOrWhiteSpace(_username)) stored=_username; if(string.IsNullOrWhiteSpace(stored)) return; _username=stored; _userId= await _db.GetUserIdAsync(_username); if(_userId==null) return; _dualHeader.Username=_username; await LoadProfileAsync(); await LoadThemeAsync(); }catch{} }
    private async Task LoadThemeAsync(){ if(_userId==null) return; var dark= await _db.GetUserThemeDarkAsync(_userId.Value); _dualHeader.SetTheme(dark ?? (Application.Current!.RequestedTheme==AppTheme.Dark), suppressEvent:true); ApplyTheme(dark ?? (Application.Current!.RequestedTheme==AppTheme.Dark)); }
    private void ApplyTheme(bool dark){ if(Application.Current is App app) app.UserAppTheme= dark? AppTheme.Dark: AppTheme.Light; _dualHeader?.SyncFromAppTheme(); }
    private async Task LoadProfileAsync(){ if(_userId==null) return; var prof= await _db.GetUserProfileAsync(_userId.Value); if(prof==null) return; _usernameEntry.Text=prof.Username; _emailEntry.Text=prof.Email??""; }
    private void BuildUi(){ var primary=(Color)Application.Current!.Resources["Primary"]; _dualHeader=new DualHeaderView{ TitleText="Manage Account", Username=_username }; _dualHeader.ThemeToggled+= async (_,dark)=> await OnThemeToggledAsync(dark); _dualHeader.LogoutRequested+= async (_,__)=> await LogoutAsync(); _dualHeader.DashboardRequested+= async (_,__)=> { try{ await Shell.Current.GoToAsync($"//dashboard?username={Uri.EscapeDataString(_username)}"); }catch{} }; _dualHeader.ManageAccountRequested+= (_,__)=>{/* already here */}; _dualHeader.ManageListsRequested+= async (_,__)=> { try{ await Shell.Current.GoToAsync($"//managelists?username={Uri.EscapeDataString(_username)}"); }catch{} }; _dualHeader.UserMenuToggleRequested+= (_,__)=> ToggleUserMenu(); _dualHeader.SetTheme(Application.Current!.RequestedTheme==AppTheme.Dark, suppressEvent:true);
        _usernameEntry=new Entry{ Placeholder="username", Style=(Style)Application.Current!.Resources["FilledEntry"]}; _emailEntry=new Entry{ Placeholder="email", Keyboard=Keyboard.Email, Style=(Style)Application.Current!.Resources["FilledEntry"]}; _currentPasswordEntry=new Entry{ Placeholder="current password", IsPassword=true, Style=(Style)Application.Current!.Resources["FilledEntry"]}; _newPasswordEntry=new Entry{ Placeholder="new password", IsPassword=true, Style=(Style)Application.Current!.Resources["FilledEntry"]}; _confirmPasswordEntry=new Entry{ Placeholder="confirm new password", IsPassword=true, Style=(Style)Application.Current!.Resources["FilledEntry"]};
        _profileMessageLabel=new Label{ TextColor=Colors.Red, IsVisible=false, FontAttributes=FontAttributes.Bold, FontSize=13};
        _passwordMessageLabel=new Label{ TextColor=Colors.Red, IsVisible=false, FontAttributes=FontAttributes.Bold, FontSize=13};
        _saveProfileButton=new Button{ Text="Save Profile", Style=(Style)Application.Current!.Resources["PrimaryButton"]}; _saveProfileButton.Clicked+= OnSaveProfileClicked; _changePasswordButton=new Button{ Text="Change Password", Style=(Style)Application.Current!.Resources["PrimaryButton"]}; _changePasswordButton.Clicked+= OnChangePasswordClicked; _loading=new ActivityIndicator{ IsVisible=false, IsRunning=false, Color=primary};
        var profileCard=new Border{ StrokeThickness=1, Stroke=primary, StrokeShape=new RoundRectangle{ CornerRadius=new CornerRadius(20)}, Padding=new Thickness(24,28), BackgroundColor=(Color)Application.Current!.Resources[Application.Current!.RequestedTheme==AppTheme.Dark?"OffBlack":"White"], Content=new VerticalStackLayout{ Spacing=10, Children={ new Label{ Text="Profile", FontAttributes=FontAttributes.Bold, FontSize=22, TextColor=primary}, new Label{ Text="Username", FontAttributes=FontAttributes.Bold}, _usernameEntry, new Label{ Text="Email", FontAttributes=FontAttributes.Bold}, _emailEntry, _profileMessageLabel, _saveProfileButton } } };
        var passwordCard=new Border{ StrokeThickness=1, Stroke=primary, StrokeShape=new RoundRectangle{ CornerRadius=new CornerRadius(20)}, Padding=new Thickness(24,28), BackgroundColor=(Color)Application.Current!.Resources[Application.Current!.RequestedTheme==AppTheme.Dark?"OffBlack":"White"], Content=new VerticalStackLayout{ Spacing=10, Children={ new Label{ Text="Change Password", FontAttributes=FontAttributes.Bold, FontSize=22, TextColor=primary}, new Label{ Text="Current Password", FontAttributes=FontAttributes.Bold}, _currentPasswordEntry, new Label{ Text="New Password", FontAttributes=FontAttributes.Bold}, _newPasswordEntry, new Label{ Text="Confirm New Password", FontAttributes=FontAttributes.Bold}, _confirmPasswordEntry, _passwordMessageLabel, _changePasswordButton } } };
        var stack=new VerticalStackLayout{ Padding=new Thickness(20,12), Spacing=20, Children={ profileCard, passwordCard, _loading } }; var scroll=new ScrollView{ Content=stack };
        _pageRoot=new Grid{ RowDefinitions=new RowDefinitionCollection{ new RowDefinition(GridLength.Auto), new RowDefinition(GridLength.Star)} }; _pageRoot.Add(_dualHeader,0,0); _pageRoot.Add(scroll,0,1);
        _pageOverlay=new AbsoluteLayout{ IsClippedToBounds=false }; AbsoluteLayout.SetLayoutBounds(_pageRoot,new Rect(0,0,1,1)); AbsoluteLayout.SetLayoutFlags(_pageRoot,AbsoluteLayoutFlags.All);
        _menuScrim=new BoxView{ BackgroundColor=Colors.Transparent, IsVisible=false, InputTransparent=true }; var scrimTap=new TapGestureRecognizer(); scrimTap.Tapped+= async (_,__)=> await HideUserMenuAsync(); _menuScrim.GestureRecognizers.Add(scrimTap); AbsoluteLayout.SetLayoutBounds(_menuScrim,new Rect(0,0,1,1)); AbsoluteLayout.SetLayoutFlags(_menuScrim,AbsoluteLayoutFlags.All);
        var menuContent=_dualHeader.GetMenuContentStack(); _userMenuBorder=new Border{ StrokeThickness=1, Stroke=Colors.White.WithAlpha(0.35f), BackgroundColor=primary.WithAlpha(0.90f), StrokeShape=new RoundRectangle{ CornerRadius=new CornerRadius(10) }, Padding=new Thickness(14,12), Content=menuContent, TranslationY=60, Opacity=0, IsVisible=false, Shadow=new Shadow{ Brush=Brush.Black, Offset=new Point(0,4), Radius=12, Opacity=0.35f }, HorizontalOptions=LayoutOptions.End, VerticalOptions=LayoutOptions.Start };
        _menuAlignGrid=new Grid{ ColumnDefinitions=new ColumnDefinitionCollection{ new ColumnDefinition(GridLength.Star), new ColumnDefinition(GridLength.Auto) }, Margin=new Thickness(0,0,6,0), InputTransparent=true, IsVisible=false }; Grid.SetColumn(_userMenuBorder,1); _menuAlignGrid.Children.Add(_userMenuBorder); var outsideTap=new TapGestureRecognizer(); outsideTap.Tapped+= async (_,__)=> { if(_userMenuVisible) await HideUserMenuAsync(); }; _menuAlignGrid.GestureRecognizers.Add(outsideTap); AbsoluteLayout.SetLayoutBounds(_menuAlignGrid,new Rect(0,0,1,1)); AbsoluteLayout.SetLayoutFlags(_menuAlignGrid,AbsoluteLayoutFlags.All);
        _pageOverlay.Children.Add(_pageRoot); _pageOverlay.Children.Add(_menuScrim); _pageOverlay.Children.Add(_menuAlignGrid); Content=_pageOverlay; }

    private async void ToggleUserMenu(){ if(string.IsNullOrWhiteSpace(_dualHeader?.Username)) return; if(_userMenuVisible) await HideUserMenuAsync(); else await ShowUserMenuAsync(); }
    private async Task ShowUserMenuAsync(){ _userMenuVisible=true; _menuScrim.IsVisible=true; _menuScrim.InputTransparent=false; _menuAlignGrid.IsVisible=true; _menuAlignGrid.InputTransparent=false; _userMenuBorder.Scale=0.85; _userMenuBorder.IsVisible=true; await Task.WhenAll(_userMenuBorder.FadeTo(1,160,Easing.CubicOut), _userMenuBorder.ScaleTo(1,160,Easing.CubicOut)); }
    private async Task HideUserMenuAsync(){ _userMenuVisible=false; await Task.WhenAll(_userMenuBorder.FadeTo(0,120,Easing.CubicOut), _userMenuBorder.ScaleTo(0.92,120,Easing.CubicOut)); _userMenuBorder.IsVisible=false; _menuAlignGrid.InputTransparent=true; _menuAlignGrid.IsVisible=false; _menuScrim.InputTransparent=true; _menuScrim.IsVisible=false; }

    private async Task LogoutAsync(){ try{ SecureStorage.Remove("AUTH_USERNAME"); }catch{} _username=""; if(_dualHeader!=null) _dualHeader.Username=""; try{ await Shell.Current.GoToAsync("//login"); }catch{} }
    private async Task OnThemeToggledAsync(bool dark){ ApplyTheme(dark); if(_userId!=null){ try{ await _db.SetUserThemeDarkAsync(_userId.Value,dark);}catch{} } }

    private async void OnSaveProfileClicked(object? sender, EventArgs e){ if(_userId==null) return; HideProfileMessage(); var newUsername=_usernameEntry.Text?.Trim()??""; var newEmail=_emailEntry.Text?.Trim()??""; if(string.IsNullOrWhiteSpace(newUsername)){ ShowProfileError("Username required"); return; } if(string.IsNullOrWhiteSpace(newEmail) || !Regex.IsMatch(newEmail,@"^[^@\s]+@[^@\s]+\.[^@\s]+$")){ ShowProfileError("Valid email required"); return; } SetBusy(true); try{ bool userOk= await _db.UpdateUsernameAsync(_userId.Value,newUsername); if(!userOk){ ShowProfileError("Username already in use"); return; } bool emailOk= await _db.UpdateEmailAsync(_userId.Value,newEmail); if(!emailOk){ ShowProfileError("Email already in use"); return; } _username=newUsername; await SecureStorage.SetAsync("AUTH_USERNAME",_username); _dualHeader.Username=_username; ShowProfileSuccess("Profile updated"); }catch(Exception ex){ ShowProfileError(ex.Message); }finally{ SetBusy(false); } }

    private async void OnChangePasswordClicked(object? sender, EventArgs e){ if(_userId==null) return; HidePasswordMessage(); var current=_currentPasswordEntry.Text??""; var np=_newPasswordEntry.Text??""; var confirm=_confirmPasswordEntry.Text??""; if(string.IsNullOrWhiteSpace(current) || string.IsNullOrWhiteSpace(np) || string.IsNullOrWhiteSpace(confirm)){ ShowPasswordError("All password fields required"); return; } if(np!=confirm){ ShowPasswordError("Passwords do not match"); return; } if(np.Length<6){ ShowPasswordError("Password too short (min 6)"); return; } SetBusy(true); try{ var ok= await _db.UpdatePasswordAsync(_userId.Value,current,np); if(!ok){ ShowPasswordError("Current password incorrect or update failed"); return; } _currentPasswordEntry.Text=""; _newPasswordEntry.Text=""; _confirmPasswordEntry.Text=""; ShowPasswordSuccess("Password changed"); }catch(Exception ex){ ShowPasswordError(ex.Message); }finally{ SetBusy(false); } }

    // Profile message helpers
    private void ShowProfileError(string msg){ _profileMessageLabel.Text=msg; _profileMessageLabel.TextColor=Colors.Red; _profileMessageLabel.IsVisible=true; }
    private void ShowProfileSuccess(string msg){ _profileMessageLabel.Text=msg; _profileMessageLabel.TextColor=Colors.Green; _profileMessageLabel.IsVisible=true; }
    private void HideProfileMessage(){ _profileMessageLabel.IsVisible=false; }
    // Password message helpers
    private void ShowPasswordError(string msg){ _passwordMessageLabel.Text=msg; _passwordMessageLabel.TextColor=Colors.Red; _passwordMessageLabel.IsVisible=true; }
    private void ShowPasswordSuccess(string msg){ _passwordMessageLabel.Text=msg; _passwordMessageLabel.TextColor=Colors.Green; _passwordMessageLabel.IsVisible=true; }
    private void HidePasswordMessage(){ _passwordMessageLabel.IsVisible=false; }

    private void SetBusy(bool busy){ _loading.IsVisible=busy; _loading.IsRunning=busy; _saveProfileButton.IsEnabled=!busy; _changePasswordButton.IsEnabled=!busy; }
}